config/routes.rb
Rails.application.routes.draw do
  resources :tide_extremes
  resources :tides
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tide.rb
require 'HTTParty'
require 'json'

class Tide < ApplicationRecord

start_date = '2021-12-22'
end_date = '2021-12-23'

lat = 43.4831519
lng = -1.558626

  def get_tide(lat, lng, start_date, end_date)
    headers = {
    "Authorization": "8902712a-5c25-11ec-b9d3-0242ac130002-89027206-5c25-11ec-b9d3-0242ac130002"
    }

    response = HTTParty.get(
      "https://api.stormglass.io/v2/tide/extremes/point?lat=#{lat}&lng=#{lng}&start=#{start_date}&end=#{end_date}",
      :headers => headers
    )

    tide_set = response["data"]

    puts "Here are the tides for the specified period : "
    puts ""
    tide_set.each do |tide_extreme|
        puts "Tide time (UTC +1) : #{Time.parse(tide_extreme["time"]).utc+1*60*60}"

        puts "Tide type : #{tide_extreme["type"]}"
        puts "Tide height : #{tide_extreme["height"]}"
        puts ""
    end
  end
end

app/models/tide_extreme.rb
# require 'HTTParty'
require 'json'

class TideExtreme < ApplicationRecord
  attr_accessor :type, :time, :height

  def get_tides(lat, lng, start_date, end_date)
    headers = {
    "Authorization": "8902712a-5c25-11ec-b9d3-0242ac130002-89027206-5c25-11ec-b9d3-0242ac130002"
    }

    response = HTTParty.get(
      "https://api.stormglass.io/v2/tide/extremes/point?lat=#{lat}&lng=#{lng}&start=#{start_date}&end=#{end_date}",
      :headers => headers
    )

    #tides is the variable storing all the tides for the specified location and time-frame
    tides = response["data"]

    puts "Here are the tides for the specified period : "

    tides.each do |tide_extreme|
        tide_extreme_time = Time.parse(tide_extreme["time"]).utc
        # use this if you only want to return UTC + 1 formatted time : tide_extreme_time = Time.parse(tide_extreme["time"]).utc+1*60*60

        tide_extreme_type = tide_extreme["type"]
        tide_extreme_height = tide_extreme["height"]
        # this loop goes through the tides in tide_set
        # and extracts the extreme_tide data
        # time of the extreme
        # type of the extreme (high, low)
        # height of the extreme

        save_tide_extreme(tide_extreme_time, tide_extreme_type, tide_extreme_height)
        #calling save_tide_extreme() to save each tide extreme into DB if it's not already there
    end
  end

  def save_tide_extreme(time, type, height)
    TideExtreme.new(time, type, height)
    puts ""
    puts "At the following time (UTC+1)  : #{tide_extreme_time}"
    puts "Tide type is : #{tide_extreme_type}"
    puts "Tide height is : #{tide_extreme_height}"
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/tide_extremes_controller.rb
class TideExtremesController < ApplicationController
  before_action :set_tide_extreme, only: %i[ show edit update destroy ]

  # GET /tide_extremes or /tide_extremes.json
  def index
    @tide_extremes = TideExtreme.all
  end

  # GET /tide_extremes/1 or /tide_extremes/1.json
  def show
  end

  # GET /tide_extremes/new
  def new
    @tide_extreme = TideExtreme.new
  end

  # GET /tide_extremes/1/edit
  def edit
  end

  # POST /tide_extremes or /tide_extremes.json
  def create
    @tide_extreme = TideExtreme.new(tide_extreme_params)

    respond_to do |format|
      if @tide_extreme.save
        format.html { redirect_to tide_extreme_url(@tide_extreme), notice: "Tide extreme was successfully created." }
        format.json { render :show, status: :created, location: @tide_extreme }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tide_extreme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tide_extremes/1 or /tide_extremes/1.json
  def update
    respond_to do |format|
      if @tide_extreme.update(tide_extreme_params)
        format.html { redirect_to tide_extreme_url(@tide_extreme), notice: "Tide extreme was successfully updated." }
        format.json { render :show, status: :ok, location: @tide_extreme }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tide_extreme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tide_extremes/1 or /tide_extremes/1.json
  def destroy
    @tide_extreme.destroy

    respond_to do |format|
      format.html { redirect_to tide_extremes_url, notice: "Tide extreme was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tide_extreme
      @tide_extreme = TideExtreme.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tide_extreme_params
      params.require(:tide_extreme).permit(:type, :time, :height)
    end
end

app/controllers/tides_controller.rb
class TidesController < ApplicationController
  before_action :set_tide, only: %i[ show edit update destroy ]

  # GET /tides or /tides.json
  def index
    @tides = Tide.all
  end

  # GET /tides/1 or /tides/1.json
  def show
  end

  # GET /tides/new
  def new
    @tide = Tide.new
  end

  # GET /tides/1/edit
  def edit
  end

  # POST /tides or /tides.json
  def create
    @tide = Tide.new(tide_params)

    respond_to do |format|
      if @tide.save
        format.html { redirect_to tide_url(@tide), notice: "Tide was successfully created." }
        format.json { render :show, status: :created, location: @tide }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tides/1 or /tides/1.json
  def update
    respond_to do |format|
      if @tide.update(tide_params)
        format.html { redirect_to tide_url(@tide), notice: "Tide was successfully updated." }
        format.json { render :show, status: :ok, location: @tide }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tides/1 or /tides/1.json
  def destroy
    @tide.destroy

    respond_to do |format|
      format.html { redirect_to tides_url, notice: "Tide was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tide
      @tide = Tide.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tide_params
      params.fetch(:tide, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TidesTrialAndErrors</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/tide_extremes/_form.html.erb
<%= simple_form_for(@tide_extreme) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tide_extremes/edit.html.erb
<h1>Editing Tide Extreme</h1>

<%= render 'form', tide_extreme: @tide_extreme %>

<%= link_to 'Show', @tide_extreme %> |
<%= link_to 'Back', tide_extremes_path %>

app/views/tide_extremes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tide Extremes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tide_extremes.each do |tide_extreme| %>
      <%= tide_extreme.time %>
      <%= tide_extreme.type %>
      <tr>
        <td><%= link_to 'Show', tide_extreme %></td>
        <td><%= link_to 'Edit', edit_tide_extreme_path(tide_extreme) %></td>
        <td><%= link_to 'Destroy', tide_extreme, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tide Extreme', new_tide_extreme_path %>

app/views/tide_extremes/new.html.erb
<h1>New Tide Extreme</h1>

<%= render 'form', tide_extreme: @tide_extreme %>

<%= form_for(@tide_extreme) do |f| %>
  <%= f.label :time %>
  <%= f.text_field :time %>
  <%= f.label :type %>
  <%= f.text_field :type %>
  <%= f.label :height %>
  <%= f.number_field :height %>
  <%= f.submit %>
<% end %>

<%= link_to 'Back', tide_extremes_path %>

app/views/tide_extremes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_tide_extreme_path(@tide_extreme) %> |
<%= link_to 'Back', tide_extremes_path %>
<h2><%= @tide_extreme.time %></h2>
<p><%= @tide_extreme.type %></p>
<p><%= @tide_extreme.height %></p>

app/views/tides/_form.html.erb
<%= simple_form_for(@tide) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tides/edit.html.erb
<h1>Editing Tide</h1>

<%= render 'form', tide: @tide %>

<%= link_to 'Show', @tide %> |
<%= link_to 'Back', tides_path %>

app/views/tides/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tides</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tides.each do |tide| %>
      <tr>
        <td><%= link_to 'Show', tide %></td>
        <td><%= link_to 'Edit', edit_tide_path(tide) %></td>
        <td><%= link_to 'Destroy', tide, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tide', new_tide_path %>

app/views/tides/new.html.erb
<h1>New Tide</h1>

<%= render 'form', tide: @tide %>

<%= link_to 'Back', tides_path %>

app/views/tides/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_tide_path(@tide) %> |
<%= link_to 'Back', tides_path %>